### PR TITLE
feature: support for intel oneAPI compiler suite

### PR DESCRIPTION
**Pull request by T31M**
- Add support for Intel oneAPI compiler suite (https://www.intel.com/content/www/us/en/developer/tools/oneapi/toolkits.html) based around LLVM, which succeedes Intel Classic Compiler (icc).
- Fix initialization of signal handler struct which prevented compilation using Intel oneAPI icx compiler with error on type casting.
- Add new toolchain for Intel oneAPI icx compiler.
- Removed unsupported warning flags.
- Left default -O3 optimizations as they were. More are available in the official documentation.

### CODE REVIEW

**Comment by JoshuaGreen** [comment]
I can't just the changes to `make*`.  Of the changes to [`platform/unix/maxtime.c`](https://github.com/thomas-maeder/popeye/pull/348/files#diff-dc008468308975b8effc863c4b4e9cb2626614f90907cc6a96d212f6ba6968cb):

1. The replacement of
```c
act.sa_mask = 0;
```
with
```c
sigemptyset(&act.sa_mask);
```
seems to be simply _correct_, the portable way to set that value.  Thanks for suggesting it.

2. The replacement of
```c
act.sa_flags = 0;
```
with
```c
sigemptyset(&act.sa_flags);
```
seems to be unjustified in general, and it disagrees with the example usage [here](https://www.gnu.org/software/libc/manual/html_node/Sigaction-Function-Example.html).  I think we should leave that line as before.

**Comment by T31M** [comment]
- Fixed a minor "c&p" issue in the `make.incl` file for icx.
- Best to my knowlege after `ln -s makefile.unx makefile` you have to manually modify `makefile.defaults` at the end (by default `TOOLCHAIN=gcc`) to switch toolchain to e.g. icx, then it uses a different suite in the toolchains folder.
- I will revisit the `act.sa_flags` topic, as I might have changed that in mistake. Let me see if the compiler is satisfied with the `act.sa_mask` part only (real C amateur here)...

Thanks for the input !

**Comment by T31M** [comment]
@JoshuaGreen reverted the change to `act.sa_flags` as it was invalid as pointed out and not required to make compilation with icx work.

**Comment by thomas-maeder** [comment]
I can't find how to pull your changes. If I try
git checkout -b T31M-feature/add-intel-oneapi-compiler-support master
git pull https://github.com/T31M/popeye.git feature/add-intel-oneapi-compiler-support
I get the sources without toolchains/icx and without the correction in platform/unix/maxtime.c

**Comment by T31M** [comment]
@thomas-maeder it believe it works like this. I hope this is what you were looking for 🙂

```
⌚(09:37:48)📁(popeye)🛠 (^master)🐍[3.10.11]☁ ⏱ [0,00s]
λ git fetch https://github.com/T31M/popeye.git feature/add-intel-oneapi-compiler-support:T31M-feature/add-intel-oneapi-compiler-support
From https://github.com/T31M/popeye
 * [new branch]          feature/add-intel-oneapi-compiler-support -> T31M-feature/add-intel-oneapi-compiler-support
 
⌚(09:39:29)📁(popeye)🛠 (^master)🐍[3.10.11]☁ ⏱ [0,40s]
λ git checkout T31M-feature/add-intel-oneapi-compiler-support
Switched to branch 'T31M-feature/add-intel-oneapi-compiler-support'

⌚(09:39:35)📁(popeye)🛠 (^T31M-feature/add-intel-oneapi-compiler-support)🐍[3.10.11]☁ ⏱ [0,03s]
λ git log
commit 85e28d9c55a13e07c66cd01a03f259670713d0a3 (HEAD -> T31M-feature/add-intel-oneapi-compiler-support)
Author: T31M <t31m@cyberstuff.com>
Date:   Thu Feb 9 17:02:46 2023 +0100

    (bugfix) revert unnecessary change to sa_flags

commit 493c86a41d5c0310e84c7abb62ad426ce46a0770
Author: T31M <t31m@cyberstuff.com>
Date:   Thu Feb 9 09:22:29 2023 +0100

    (chore) Update requirement description in make.incl for icx toolchain

commit 585028886c2d443b292e05499bf586399446f516
Author: T31M <t31m@cyberstuff.com>
Date:   Wed Feb 8 19:53:22 2023 +0100

    feature: support for intel oneAPI compiler suite

commit 0abdeef1b45c91ee01d24e04b606c30200448910 (tag: v4.87)
Merge: 682c32dba 0b31713ce
Author: Thomas Maeder <maeder+github@glue.ch>
Date:   Sat Jun 26 09:10:14 2021 +0200

    Merge branch 'release/4.87'
```

**Review by thomas-maeder — APPROVED** [review]

**Comment by thomas-maeder** [comment]
I have just merged this pull request into branch develop.

Thanks!

**Comment by T31M** [comment]
Thanks for approving. @thomas-maeder 

Although retargeting to "develop" branch could have been commented / easily changed, if requested.

Now the changes were pulled in "behind my back" and with the PR/Merge Request never actually completing (but getting closed) this "robs" me of my contribution to the project / overall GitHub statistics.

In the end I don't care that much, but for future reference, IMHO review & approval should leave the merge process & closing of the issue to the PR/Merge Request Author.

Just some closing thoughts....

**Pull request closed without merging**
